[build]
  command = "pip install -r requirements.txt"
  publish = "web/backend"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
