[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "gcc", "gnumake"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python web/backend/modern_server.py --host 0.0.0.0 --port $PORT"
