services:
  - type: web
    name: polyrun
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd web/backend && python modern_server.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
